<?php

namespace App\Models\Yx;

use Encore\Admin\Traits\AdminBuilder;
use Encore\Admin\Traits\ModelTree;
use Illuminate\Database\Eloquent\Model;
use Wanjia\Common\Database\ExModel;

class YxFunc extends Model
{
    use ExModel,ModelTree,AdminBuilder;

    protected $table = 'yx_func';

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
        $this->titleColumn = 'name';
        $this->orderColumn = 'sort';
    }

    public static function otherSelects()
    {
        $options = (new static())->buildSelectOptions();
        return collect($options)->all();
    }

    public function classicCases()
    {
        return $this->belongsToMany(YxClassicCase::class, 'yx_classic_case_func', 'func_id', 'case_id');
    }

    public function tempCases()
    {
        return $this->belongsToMany(YxTempCase::class, 'yx_temp_case_func', 'func_id', 'case_id');
    }

    protected static function boot()
    {
        static::deleted(function(YxFunc $func) {
           $func->classicCases()->detach();
           $func->tempCases()->detach();
        });
        parent::boot(); // TODO: Change the autogenerated stub
    }

}
